### ISSUE TITLE
calculateGravityAccel function

### ISSUE THREAD

**Issue by gabbersonger** [NimuKaT/Simple-planetary-system-sim#14]
`function calculateGravityAccel(x1, y1, x2, y2, mass, dist, angle) {`
`// get the effective acceleration on object 1 due to object 2`
`var magnitude = (mass)/Math.pow(dist, 2);`
`var yMag = magnitude*Math.sin(angle*Math.PI/180);`
`var xMag = magnitude*Math.cos(angle*Math.PI/180);`
`return [xMag, yMag];`
`}`

this is a function currently, and it needs x1, y1, x2, y2 but never uses them. Is this an error or does it use it somewhere?

**Comment by NimuKaT** [comment]
Yeah you don't need it. I've already removed it in another branch but you might as well remove it.
