### ISSUE TITLE
Velocity Problem

### ISSUE THREAD

**Issue by gabbersonger** [NimuKaT/Simple-planetary-system-sim#7]
I saw the problem, Takumi found it:

```
this.setVelocity = function(vx, vy) {
    return this.vx = vx;
    return this.vy = vy;
}
```

Shouldn't return twice, otherwise screws up velocity.

**Comment by Naidah** [comment]
That should only matter if you try setting the velocity, but I'm 90% sure I got the orbits working now, so we just need to put everything together

**Comment by Naidah** [comment]
You can just remove the returns by the way, its meant to set the velocities, ot return

**Comment by gabbersonger** [comment]
Yea thats what I did, works very well now

**Comment by Naidah** [comment]
Want to do a merge now

**Comment by gabbersonger** [comment]
Yep if you could do that it would be great but just change the velocity thing to remove the returns and then merge that in.

**Comment by Naidah** [comment]
already done that, just forgot how to merge to master, is there an easier way we could talk?

**Comment by gabbersonger** [comment]
facebook? or you can text me on 0406970081 or if you can think of a better way

**Comment by Naidah** [comment]
facebook I guess, mabye skype but can't really be bothered to set it up right now
